"""Theme metadata and local theme storage helpers."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from .config import Paths, assert_valid_name


@dataclass
class ThemeMetadata:
    name: str
    author: str = ""
    description: str = ""
    tags: list[str] = field(default_factory=list)

    @staticmethod
    def from_toml_text(text: str, fallback_name: str) -> "ThemeMetadata":
        """Very small, dependency-free TOML reader for the flat
        key = value metadata files this project uses. Good enough for
        the four fields we actually need.
        """
        name = fallback_name
        author = ""
        description = ""
        tags: list[str] = []
        for line in text.splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip()
            if key == "name":
                name = value.strip('"').strip("'") or name
            elif key == "author":
                author = value.strip('"').strip("'")
            elif key == "description":
                description = value.strip('"').strip("'")
            elif key == "tags":
                inner = value.strip("[]")
                tags = [
                    part.strip().strip('"').strip("'")
                    for part in inner.split(",")
                    if part.strip()
                ]
        return ThemeMetadata(name=name, author=author, description=description, tags=tags)


def _bundled_metadata_dir() -> Path | None:
    """Locates the metadata/ directory bundled alongside this package,
    whether running from a source checkout, an editable install, or an
    installed wheel/sdist.
    """
    import importlib.resources

    # 1. Development layout: repo_root/metadata next to repo_root/startheme
    here = Path(__file__).resolve().parent
    candidate = here.parent / "metadata"
    if candidate.is_dir():
        return candidate

    # 2. Installed package data (see [tool.setuptools.package-data] /
    # MANIFEST.in): startheme/metadata/*.toml shipped inside the package.
    try:
        packaged = importlib.resources.files("startheme") / "metadata"
        if packaged.is_dir():
            return Path(str(packaged))
    except (ModuleNotFoundError, TypeError):
        pass

    return None


def builtin_catalog() -> list[ThemeMetadata]:
    """The local catalog of themes startheme knows about without
    talking to the network: read from the metadata/ directory shipped
    with this package. Falls back to a minimal hardcoded list only if
    that directory cannot be found at all (e.g. an unusual install).
    """
    metadata_dir = _bundled_metadata_dir()
    if metadata_dir is None:
        return [
            ThemeMetadata(
                name="cute",
                author="startheme",
                description="Soft pastel pink developer theme",
                tags=["pink", "cute", "minimal"],
            ),
            ThemeMetadata(
                name="cyber",
                author="startheme",
                description="Dark hacker inspired theme",
                tags=["dark", "hacker", "neon"],
            ),
            ThemeMetadata(
                name="professional",
                author="startheme",
                description="Clean enterprise theme",
                tags=["clean", "minimal", "corporate"],
            ),
        ]

    catalog = []
    for path in sorted(metadata_dir.glob("*.toml")):
        text = path.read_text()
        catalog.append(ThemeMetadata.from_toml_text(text, fallback_name=path.stem))
    return catalog


def list_installed(paths: Paths) -> list[str]:
    if not paths.themes_dir.exists():
        return []
    names = sorted(p.stem for p in paths.themes_dir.glob("*.toml"))
    return names


def is_installed(paths: Paths, name: str) -> bool:
    return paths.theme_path(name).exists()


def read_theme_contents(paths: Paths, name: str) -> str:
    path = paths.theme_path(name)
    if not path.exists():
        raise FileNotFoundError(f"theme '{name}' is not installed")
    return path.read_text()


def starter_template(name: str, author: str) -> str:
    """A working starter starship.toml for `startheme create <name>`."""
    return f'''# Theme: {name}
# Author: {author}
# Generated by startheme create {name}
#
# Tip: run `startheme edit {name}` to keep working on this,
# and `startheme apply {name}` when you are happy with it.

format = """
[](#6272a4)\\
$os\\
$username\\
[](bg:#44475a fg:#6272a4)\\
$directory\\
[](fg:#44475a bg:#282a36)\\
$git_branch\\
$git_status\\
[](fg:#282a36 bg:#1e1f29)\\
$nodejs\\
$rust\\
$python\\
[](fg:#1e1f29)\\
$line_break$character
"""

[os]
disabled = false
style = "bg:#6272a4 fg:#f8f8f2"

[username]
show_always = true
style_user = "bg:#6272a4 fg:#f8f8f2"
style_root = "bg:#6272a4 fg:#ff5555"
format = "[ $user ]($style)"

[directory]
style = "bg:#44475a fg:#f8f8f2"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = true

[git_branch]
style = "bg:#282a36 fg:#50fa7b"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:#282a36 fg:#f1fa8c"
format = "[$all_status$ahead_behind ]($style)"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
'''


def create_theme(paths: Paths, name: str, author: str, force: bool = False) -> None:
    assert_valid_name(name)
    path = paths.theme_path(name)
    if path.exists() and not force:
        raise FileExistsError(
            f"theme '{name}' already exists at {path} (use --force to overwrite)"
        )
    paths.ensure_dirs()
    path.write_text(starter_template(name, author))


def remove_theme_file(paths: Paths, name: str) -> None:
    path = paths.theme_path(name)
    if not path.exists():
        raise FileNotFoundError(f"theme '{name}' is not installed")
    path.unlink()
